#!/usr/bin/env python3
"""Call sequence differences from collinear BLAST blocks refined with MAFFT.

The script compares a query assembly with a reference assembly. BLAST outfmt 6
records define collinear blocks, MAFFT refines each block, and the resulting
SNVs, insertions, and deletions are reported in a coordinate-aware TSV file.
"""

from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import tempfile
from pathlib import Path

from Bio import AlignIO, SeqIO


BLAST_COLUMNS = (
    "qseqid", "sseqid", "pident", "length", "mismatch", "gapopen",
    "qstart", "qend", "sstart", "send", "evalue", "bitscore",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Identify SNVs and indels between two mitochondrial assemblies "
            "using BLAST collinear blocks and MAFFT refinement."
        )
    )
    parser.add_argument("--query", required=True, type=Path, help="Query FASTA file")
    parser.add_argument("--reference", required=True, type=Path, help="Reference FASTA file")
    parser.add_argument(
        "--blast", required=True, type=Path,
        help="BLAST tabular file in standard outfmt 6 (12 columns)",
    )
    parser.add_argument("--output", required=True, type=Path, help="Output TSV file")
    parser.add_argument("--query-id", help="Query sequence ID; defaults to the first FASTA record")
    parser.add_argument("--reference-id", help="Reference sequence ID; defaults to the first FASTA record")
    parser.add_argument("--min-block-length", type=int, default=100)
    parser.add_argument("--min-identity", type=float, default=0.0, help="Minimum BLAST percent identity")
    parser.add_argument("--mafft", default="mafft", help="MAFFT executable or path")
    parser.add_argument(
        "--keep-overlapping-calls", action="store_true",
        help="Keep duplicate calls generated by overlapping BLAST blocks",
    )
    return parser.parse_args()


def load_record(path: Path, requested_id: str | None):
    records = list(SeqIO.parse(path, "fasta"))
    if not records:
        raise ValueError(f"No FASTA records found in {path}")
    if requested_id is None:
        return records[0]
    for record in records:
        if record.id == requested_id:
            return record
    raise ValueError(f"Sequence ID {requested_id!r} not found in {path}")


def read_blast(path: Path, query_id: str, reference_id: str, min_length: int, min_identity: float):
    blocks = []
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip() or line.startswith("#"):
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 12:
                fields = line.split()
            if len(fields) < 12:
                raise ValueError(f"{path}:{line_number}: expected at least 12 BLAST columns")
            row = dict(zip(BLAST_COLUMNS, fields[:12]))
            if row["qseqid"] != query_id or row["sseqid"] != reference_id:
                continue
            if int(row["length"]) < min_length or float(row["pident"]) < min_identity:
                continue
            for key in ("qstart", "qend", "sstart", "send", "length"):
                row[key] = int(row[key])
            row["pident"] = float(row["pident"])
            row["bitscore"] = float(row["bitscore"])
            blocks.append(row)
    blocks.sort(key=lambda row: (min(row["sstart"], row["send"]), -row["bitscore"]))
    return blocks


def run_mafft(query_sequence: str, reference_sequence: str, executable: str):
    with tempfile.TemporaryDirectory(prefix="mitogenome_variants_") as tmp:
        input_path = Path(tmp) / "block.fasta"
        output_path = Path(tmp) / "block.aligned.fasta"
        input_path.write_text(
            f">query\n{query_sequence}\n>reference\n{reference_sequence}\n",
            encoding="ascii",
        )
        with output_path.open("w", encoding="ascii") as output:
            subprocess.run(
                [executable, "--auto", "--quiet", str(input_path)],
                stdout=output,
                check=True,
            )
        alignment = AlignIO.read(output_path, "fasta")
    aligned = {record.id: str(record.seq).upper() for record in alignment}
    return aligned["query"], aligned["reference"]


def advance_query(position: int, strand: str, amount: int = 1) -> int:
    return position + amount if strand == "+" else position - amount


def variants_from_alignment(
    query_aligned: str,
    reference_aligned: str,
    query_start: int,
    query_end: int,
    reference_start: int,
    strand: str,
    block_id: str,
):
    reference_position = reference_start
    query_position = query_start if strand == "+" else query_end
    variants = []
    index = 0

    while index < len(reference_aligned):
        query_base = query_aligned[index]
        reference_base = reference_aligned[index]

        if query_base == reference_base:
            if reference_base != "-":
                reference_position += 1
            if query_base != "-":
                query_position = advance_query(query_position, strand)
            index += 1
            continue

        if query_base != "-" and reference_base != "-":
            variants.append({
                "reference_start": reference_position,
                "reference_end": reference_position,
                "query_start": query_position,
                "query_end": query_position,
                "ref": reference_base,
                "alt": query_base,
                "variant_type": "SNV",
                "strand": strand,
                "block_id": block_id,
            })
            reference_position += 1
            query_position = advance_query(query_position, strand)
            index += 1
            continue

        if reference_base == "-":
            inserted = []
            insertion_positions = []
            while index < len(reference_aligned) and reference_aligned[index] == "-":
                if query_aligned[index] != "-":
                    inserted.append(query_aligned[index])
                    insertion_positions.append(query_position)
                    query_position = advance_query(query_position, strand)
                index += 1
            variants.append({
                "reference_start": reference_position - 1,
                "reference_end": reference_position,
                "query_start": min(insertion_positions),
                "query_end": max(insertion_positions),
                "ref": "",
                "alt": "".join(inserted),
                "variant_type": "insertion",
                "strand": strand,
                "block_id": block_id,
            })
            continue

        deleted = []
        deletion_start = reference_position
        while index < len(query_aligned) and query_aligned[index] == "-":
            if reference_aligned[index] != "-":
                deleted.append(reference_aligned[index])
                reference_position += 1
            index += 1
        variants.append({
            "reference_start": deletion_start,
            "reference_end": reference_position - 1,
            "query_start": query_position,
            "query_end": query_position,
            "ref": "".join(deleted),
            "alt": "",
            "variant_type": "deletion",
            "strand": strand,
            "block_id": block_id,
        })

    return variants


def main() -> None:
    args = parse_args()
    if shutil.which(args.mafft) is None and not Path(args.mafft).exists():
        raise SystemExit(f"MAFFT executable not found: {args.mafft}")

    query = load_record(args.query, args.query_id)
    reference = load_record(args.reference, args.reference_id)
    blocks = read_blast(
        args.blast, query.id, reference.id, args.min_block_length, args.min_identity
    )
    if not blocks:
        raise SystemExit("No BLAST blocks passed the filters and sequence-ID checks")

    calls = []
    for number, block in enumerate(blocks, 1):
        q_low, q_high = sorted((block["qstart"], block["qend"]))
        r_low, r_high = sorted((block["sstart"], block["send"]))
        query_direction = 1 if block["qend"] >= block["qstart"] else -1
        reference_direction = 1 if block["send"] >= block["sstart"] else -1
        strand = "+" if query_direction == reference_direction else "-"

        query_sequence = query.seq[q_low - 1:q_high]
        if strand == "-":
            query_sequence = query_sequence.reverse_complement()
        reference_sequence = reference.seq[r_low - 1:r_high]
        q_aligned, r_aligned = run_mafft(
            str(query_sequence).upper(), str(reference_sequence).upper(), args.mafft
        )
        calls.extend(
            variants_from_alignment(
                q_aligned, r_aligned, q_low, q_high, r_low, strand, f"block_{number:05d}"
            )
        )

    if not args.keep_overlapping_calls:
        unique = {}
        for call in calls:
            key = tuple(call[column] for column in (
                "reference_start", "reference_end", "query_start", "query_end",
                "ref", "alt", "variant_type", "strand",
            ))
            unique.setdefault(key, call)
        calls = list(unique.values())

    calls.sort(key=lambda call: (
        call["reference_start"], call["reference_end"], call["variant_type"], call["alt"]
    ))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    columns = [
        "reference_id", "query_id", "reference_start", "reference_end",
        "query_start", "query_end", "ref", "alt", "variant_type", "strand", "block_id",
    ]
    with args.output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, delimiter="\t")
        writer.writeheader()
        for call in calls:
            writer.writerow({"reference_id": reference.id, "query_id": query.id, **call})

    print(f"Wrote {len(calls)} nonredundant variants to {args.output}")


if __name__ == "__main__":
    main()
